services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.3.0 # 
    container_name: mealie
    restart: unless-stopped
    ports:
        - "9925:9000" # 
    networks:
      - proxy
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - /docker/mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "true"
      PUID: 1000
      PGID: 1000
      TZ: America/Anchorage
      BASE_URL: https://recipes.rjester.us
    labels:
     - traefik.enable=true
     - traefik.http.routers.mealie.rule=Host(`recipes.rjester.us`)
     - traefik.http.routers.mealie.entrypoints=https
     - traefik.http.routers.mealie.tls=true
     #- traefik.http.services.mealie.loadbalancer.server.port=9925

networks:
  proxy:
    external: true