services:
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.retention.time=7d
      - --storage.tsdb.retention.size=2GB
    ports:
      - 9090:9090
    networks:
      - proxy
    volumes:
      - /docker/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yaml:ro
      - /docker/prometheus:/prometheus
    restart: unless-stopped
    labels:
     - homepage.group=Analytics
     - homepage.name=Prometheus
     - homepage.icon=prometheus.png
     - homepage.href=https://prometheus.rjester.us/
     - homepage.description=Prometheus
     - traefik.enable=true
     - traefik.http.routers.prometheus.rule=Host(`prometheus.rjester.us`)
     - traefik.http.routers.prometheus.entrypoints=https
     - traefik.http.routers.prometheus.tls=true
     - traefik.http.services.prometheus.loadbalancer.server.port=9090

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)'
    ports:
      - "9100:9100"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true