networks:
  proxy:
    external: true

services:
  server:
    image: docker.gitea.com/gitea:1.24.6
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: unless-stopped
    labels:
     - traefik.enable=true
     - traefik.http.routers.gitea.rule=Host(`git.rjester.us`)
     - traefik.http.routers.gitea.entrypoints=https
     - traefik.http.routers.gitea.tls=true
     #- traefik.http.services.gitea.loadbalancer.server.port=8091
    networks:
      - proxy
    volumes:
      - /docker/gitea/gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8091:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - proxy
    volumes:
      - /docker/gitea//gitea_db_data:/var/lib/postgresql/data

volumes:
  gitea_db_data:
  gitea_data: