version: "3.8"

secrets:
  cloudflare-api:
    file: ${DOCKERDIR}/cloudflare-api.key

services:
  traefik:
    image: docker.io/library/traefik:v3.3.4
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # --> (Optional) Enable Dashboard, don't do in production
      - 8080:8080
      # <--
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ${DOCKERDIR}/config/:/etc/traefik/:ro
      - ${DOCKERDIR}/certs/:/var/traefik/certs/:rw
    environment:
      - CF_DNS_API_TOKEN=your-cloudflare-api-token  # <-- Change this to your Cloudflare API Token
    networks:
      - frontend
    restart: unless-stopped

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

networks:
  frontend:
    external: true  # <-- (Optional) Change this to false if you want to create a new network